# prefix + I install plugins after sourcing


if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

set -sg escape-time 10


set -g mouse on
set-window-option -g mode-keys vi
set -g history-limit 10000
set -g base-index 0
setw -g pane-base-index 0

set -g status-position bottom
set -g status-interval 5
set -g status-left " #S "
set -g status-right " %H:%M %d-%b "

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'Morantron/tmux-fingers'
# Start tmux fingers by pressing Alt+F
bind -n M-f run -b "#{@fingers-cli} start #{pane_id}"


set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding
set -g @vim_navigator_prefix_mapping_clear_screen ""



run '~/.tmux/plugins/tpm/tpm'
